/*
* Author: Tim Garrison
* URI: http://mitnosirrag.tumblr.com
* GitHub: https://github.com/mitnosirrag
* License: Apache 2.0 <http://www.apache.org/licenses/LICENSE-2.0>
*/
(function(b){b.mnTextSelector={};b.fn.mnTextSelector=function(c){function k(){var a="";window.getSelection?a=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(a=document.selection.createRange().text);return a}function n(){var a=document.selection,d=0,e=0;a?"Control"!=a.type&&(a=a.createRange(),a.collapse(!0),document.addEventListener?(d=b(window).scrollLeft(),e=b(window).scrollTop()):(d=document.documentElement&&document.documentElement.scrollLeft||document.body.scrollLeft,
e=document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop),d=a.boundingLeft+d,e=a.boundingTop+e):window.getSelection&&(a=window.getSelection(),a.rangeCount&&(a=a.getRangeAt(0).cloneRange(),a.getClientRects&&(a.collapse(!0),a=a.getClientRects()[0],d=a.left+b(window).scrollLeft(),e=a.top+b(window).scrollTop())));return{x:d,y:e}}c=b.extend({fontSize:10,fontColor:"#fff",backgroundColor:"#000",hoverBackgroundColor:"rgb(80,25,180)",border:"1px solid #000",highlightBorder:"1px solid #ccc"},
c);var f=[],h={border:c.border,position:"absolute",overflow:"hidden"},l={fontSize:c.fontSize,backgroundColor:c.backgroundColor,border:c.border,borderTop:c.highlightBorder,color:c.fontColor,padding:"5px 8px","float":"left"},p={backgroundColor:c.hoverBackgroundColor};b.mnTextSelector.showOptions=function(){var a=n();h.top=a.y;h.left=a.x;var d=k(),d=encodeURIComponent(d),a='<div class="mnTextSelector">';if(f.length)for(var e,c,g=0;g<f.length;g++)e=f[g].label,c=f[g].callback,"function"==typeof c&&(b.mnTextSelector.tempMethod=
function(a){f[a].callback.call(this,d)},c='javascript:;" onclick="$.mnTextSelector.tempMethod('+g+")"),a+='<a href="'+c+'">'+e+"</a>";else a+="<span>No options available...</span>";b(a+"</div>").css(h).appendTo("body").show();b(".mnTextSelector").find("a, span").css(l);b(".mnTextSelector").find("a").on("mouseover",function(){b(this).css(p)}).on("mouseout",function(){b(this).css(l)})};b.mnTextSelector.hideOptions=function(){b(".mnTextSelector").remove()};b.mnTextSelector.addOption=function(a,b){var c=
{};c.label=a;c.callback=b;f[f.length]=c};var m;return this.each(function(){b(this).mouseup(function(a){b.mnTextSelector.hideOptions();clearTimeout(m);m=setTimeout(function(){""!=k()&&b.mnTextSelector.showOptions()},500)});b(document).click(function(){b.mnTextSelector.hideOptions()})})}})(jQuery);
